Fwmt 428 last updated added to jobs table
ONSdigital/fwmt-resource-service pull request #26
Opened 2018-07-17 14:37 UTC by ChrisHardmanONS

added changes to data base through liquibase v18, also added new column to job dto and entity

2018-07-17 14:55 UTC, soundargit requested changes
add test and fix build

2018-07-19 11:37 UTC, ChrisHardmanONS reviewed
done

2018-07-19 13:36 UTC, soundargit requested changes

2018-07-19 13:36 UTC, soundargit commented on src/integrationTest/java/uk/gov/ons/fwmt/resource_service/controller/JobControllerIT.java
>  public class JobControllerIT {
Check/expect for the values  in all rest operation test.

2018-07-19 13:36 UTC, soundargit commented on src/test/java/uk/gov/ons/fwmt/resource_service/controller/JobControllerTest.java
>  public class JobControllerTest {
add the expected value in all respective tests

2018-07-20 15:15 UTC, soundargit requested changes

2018-07-20 15:15 UTC, soundargit commented on src/integrationTest/java/uk/gov/ons/fwmt/resource_service/controller/JobControllerIT.java
>          (put("/jobs")).contentType(MediaType.APPLICATION_JSON).content(JOB_JSON).with(httpBasic("user", "password")));
add the expected in updateJobIT

2018-07-23 10:59 UTC, soundargit approved these changes

2018-07-23 10:59 UTC, merged